name = "DarrylGamrothRegistry"
uuid = "f1b7c622-974f-40ab-8efd-04e6e7c951d8"
repo = "https://github.com/DarrylGamroth/PackageRegistry.git"
description = "Darryl Gamroth's Julia Package Repository"

[packages]
0625e100-946b-11ec-09cd-6328dd093154 = { name = "ValSplit", path = "V/ValSplit" }
0974bddb-ffe7-4d59-96d4-d2a78da66510 = { name = "Dithering", path = "D/Dithering" }
0b0e1d30-6475-4286-a107-4b7aba88ddd2 = { name = "SymbolConverters", path = "S/SymbolConverters" }
1e3e096f-6c67-414b-b19e-57dba9f71c96 = { name = "BGAPI2", path = "B/BGAPI2" }
429efccb-d15f-50bf-9ef5-16fe0de80da4 = { name = "AlpaoSDK_jll", path = "jll/A/AlpaoSDK_jll" }
5c25fbc6-c823-4e8d-82ee-a726f35d2972 = { name = "StaticKV", path = "S/StaticKV" }
6b5ade5d-6e95-4584-b343-73eec2e8782b = { name = "Clocks", path = "C/Clocks" }
85e1e58a-8f06-47dc-8621-d49759448faa = { name = "AndorSDK2", path = "A/AndorSDK2" }
8c1bab52-a7d1-42b0-bb60-b0a7d7edcd1b = { name = "SpidersFragmentFilters", path = "S/SpidersFragmentFilters" }
942aeb66-1abd-4b3e-88de-97d1762fce18 = { name = "RtcFramework", path = "R/RtcFramework" }
9d30338e-3560-4e91-a403-22803ac6b660 = { name = "SpidersMessageCodecs", path = "S/SpidersMessageCodecs" }
ae4ab49b-60bf-4949-b8fd-fb49b1a0d067 = { name = "Hsm", path = "H/Hsm" }
aebde43d-366d-4353-b020-04442e269197 = { name = "TimerWheels", path = "T/TimerWheels" }
b5db94cf-04c1-4db7-9b05-47f582871ea8 = { name = "SBE", path = "S/SBE" }
b850ffb1-6704-484e-996b-4710e2f097f0 = { name = "Aeron", path = "A/Aeron" }
bf3b237f-d17d-557f-97f1-1eb158fbe9f2 = { name = "AndorSDK2_jll", path = "jll/A/AndorSDK2_jll" }
c8c55f4a-6010-44cd-a616-9e5fc16aded6 = { name = "ASDK", path = "A/ASDK" }
e50cd564-cd50-4a17-94cb-358ff85669a4 = { name = "SpidersSendEvent", path = "S/SpidersSendEvent" }
ee304b73-0f67-4038-8e67-62078cd066f9 = { name = "Aravis", path = "A/Aravis" }
f7939a7f-2bcc-4096-952b-c44031b5533b = { name = "Agent", path = "A/Agent" }
f9ebe2b0-2178-47c6-b9d1-20f9bee126a8 = { name = "SnowflakeId", path = "S/SnowflakeId" }
fde616d6-7f4b-4e2f-8ecf-0dc858f51131 = { name = "AndorSDK2CameraService", path = "A/AndorSDK2CameraService" }
